I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 13, in script call
    call neg1
  File "game/neg1.rpy", line 33, in script call
    call A1
  File "game/script.rpy", line 13, in script call
    call neg1
  File "game/neg1.rpy", line 33, in script call
    call A1
ScriptError: could not find label 'A1'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 13, in script call
    call neg1
  File "game/neg1.rpy", line 33, in script call
    call A1
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\ast.py", line 1705, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 13, in script call
    call neg1
  File "game/neg1.rpy", line 33, in script call
    call A1
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'A1'.

Windows-10-10.0.19043 AMD64
Ren'Py 8.0.1.22070801
AAA 1.0
Thu Nov 24 14:07:11 2022
