I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 19, in script call
    call neg1 from _call_neg1
  File "game/siA.rpy", line 2036, in script call
    $ end('sxA23')
  File "game/script.rpy", line 19, in script call
    call neg1 from _call_neg1
  File "game/siA.rpy", line 2036, in script call
    $ end('sxA23')
ScriptError: could not find label 'main_menu'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\Applications\Sys\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "D:\Applications\Sys\renpy-8.0.3-sdk\renpy\main.py", line 660, in main
    run(restart)
  File "D:\Applications\Sys\renpy-8.0.3-sdk\renpy\main.py", line 146, in run
    renpy.execution.run_context(True)
  File "D:\Applications\Sys\renpy-8.0.3-sdk\renpy\execution.py", line 938, in run_context
    context.run()
  File "game/script.rpy", line 19, in script call
    call neg1 from _call_neg1
  File "game/siA.rpy", line 2036, in script call
    $ end('sxA23')
  File "game/script.rpy", line 19, in script call
    call neg1 from _call_neg1
  File "game/siA.rpy", line 2036, in script call
    $ end('sxA23')
  File "D:\Applications\Sys\renpy-8.0.3-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'main_menu'.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Goodbye 0.2.4.29
Wed Dec 28 18:34:05 2022
