I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 15, in script call
    call neg1 from _call_neg1
  File "game/script.rpy", line 4, in script
    python:
  File "game/script.rpy", line 13, in <module>
    renpy.jump(label1)
NameError: name 'label1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 15, in script call
    call neg1 from _call_neg1
  File "game/script.rpy", line 4, in script
    python:
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\python.py", line 1049, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 13, in <module>
    renpy.jump(label1)
NameError: name 'label1' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.1.22070801
AAA 0.0.3.23
Sat Dec 17 12:51:32 2022
