I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/tl/Chinese/neg1.rpy", line 98, in script
    old "Feng Qiuyue"
  File "game/tl/Chinese/neg1.rpy", line 98, in script
    old "Feng Qiuyue"
Exception: A translation for "Feng Qiuyue" already exists at game/tl/Chinese/common.rpy:5.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\bootstrap.py", line 274, in bootstrap
    renpy.main.main()
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/tl/Chinese/neg1.rpy", line 98, in script
    old "Feng Qiuyue"
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/tl/Chinese/neg1.rpy", line 98, in script
    old "Feng Qiuyue"
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\ast.py", line 2751, in execute
    renpy.translation.add_string_translation(self.language, self.old, self.new, newloc)
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\translation\__init__.py", line 475, in add_string_translation
    stl.add(old, new, newloc)
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\translation\__init__.py", line 415, in add
    raise Exception("A translation for \"{}\" already exists at {}:{}.".format(
Exception: A translation for "Feng Qiuyue" already exists at game/tl/Chinese/common.rpy:5.

Windows-10-10.0.19043 AMD64
Ren'Py 8.0.1.22070801
AAA 0.0.2.14
Mon Dec  5 11:04:13 2022
